stages:
  - build

docker_build:
  stage: build
  script:
    - docker build -t leokuan/webhook-app:latest .
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker push leokuan/webhook-app:latest
