apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webhook-app
  name: webhook-app
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webhook-app
    spec:
      containers:
      - image: leokuan/webhook-app:latest
        name: webhook-app
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webhook-app
  name: webhook-app-svc
  namespace: gitlab
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webhook-app
  type: LoadBalancer
